// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments

using System.Globalization;
using Ninject.Modules;
using BAF.Common.Localization.Metadata;
using BAF.Common.Specifications;

namespace BAF.Common.Localization.Generated
{
}

namespace BAF.Common.Localization
{
	public interface ICommonResource : IResource
	{
		string Id { get; }
		string Version { get; }
		string DateCreated { get; }
		string CreatedBy { get; }
		string LastModified { get; }
		string ModifiedBy { get; }
	
	}
	public abstract class CommonSubResource
    {
        protected readonly ICommonResource Resource;

        protected CommonSubResource(ICommonResource localizationResource)
        {
            Resource = localizationResource;
        }
    }
	public partial class CommonResource : ICommonResource
	{
		private readonly IResourceCache _localizationCache;

		public CommonResource(IResourceCache locCache)  
		{
			_localizationCache = locCache;
		}
		public string GetResource(string path)
        {
            return _localizationCache.GetResource(CultureInfo.CurrentUICulture.Name, path);
        }
		public string GetResource(ISubResource subResource)
        {
            return subResource.ToString();
        }
		public string Id 
		{ 
			get { return GetResource(CommonResourcePaths.Id); } 
		}
		public string Version 
		{ 
			get { return GetResource(CommonResourcePaths.Version); } 
		}
		public string DateCreated 
		{ 
			get { return GetResource(CommonResourcePaths.DateCreated); } 
		}
		public string CreatedBy 
		{ 
			get { return GetResource(CommonResourcePaths.CreatedBy); } 
		}
		public string LastModified 
		{ 
			get { return GetResource(CommonResourcePaths.LastModified); } 
		}
		public string ModifiedBy 
		{ 
			get { return GetResource(CommonResourcePaths.ModifiedBy); } 
		}
	}

	public class CommonResourceRegistration : NinjectModule
    {
        public override void Load()
        {
            Bind<ICommonResource>().To<CommonResource>().InSingletonScope();
        }
    }
}
namespace BAF.Common.Localization.Metadata
{
	public static class CommonResourcePaths
	{
		public const string Id = "Common.Id";
		public const string Version = "Common.Version";
		public const string DateCreated = "Common.DateCreated";
		public const string CreatedBy = "Common.CreatedBy";
		public const string LastModified = "Common.LastModified";
		public const string ModifiedBy = "Common.ModifiedBy";
	}
}
