//----------------------
// <auto-generated>
//    Generated by T4FluentNH.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using FluentNHibernate.Automapping;
using FluentNHibernate.Mapping;
//<EntityProjectItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><EntityFullName>PowerArhitecture.Authentication.Entities.RolePermission&lt;TUser, TUserRole, TRole, TRolePermission, TPermissionPattern, TOrganization, TOrganizationRole&gt;</EntityFullName><EntityFilePaths><string>Entities\RolePermission.cs</string></EntityFilePaths><OverrideFilePaths /><GeneratedFilePath>RolePermission(TUser_ TUserRole_ TRole_ TRolePermission_ TPermissionPattern_ TOrganization_ TOrganizationRole).generated.cs</GeneratedFilePath></EntityProjectItem>
namespace PowerArhitecture.Authentication.Entities
{
    [GeneratedCode("T4Template", "1.0")]
    public partial class RolePermission<TUser,  TUserRole,  TRole,  TRolePermission,  TPermissionPattern,  TOrganization,  TOrganizationRole>
    {

        #region Permission


        #endregion


        private void ResetField<T>(ref T field, T value, ref bool synthIsSetField)
        {
            field = value;
            synthIsSetField = false;
        }
    }
}
