
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments

using System;
using Ninject.Modules;
using PowerArhitecture.Common.Configuration;


namespace PowerArhitecture.Authentication.Generated
{
	public static class AuthenticationSettingKeys
	{
		public const string SystemUserPassword = "PowerArhitecture.Authentication.SystemUserPassword:string";
		public const string SystemUserName = "PowerArhitecture.Authentication.SystemUserName:string";
		public const string UserClass = "PowerArhitecture.Authentication.UserClass:string";
		public const string OrganizationClass = "PowerArhitecture.Authentication.OrganizationClass:string";
		public const string AdditionalUserIncludes = "PowerArhitecture.Authentication.AdditionalUserIncludes:string";
	}
}


namespace PowerArhitecture.Authentication.Generated
{
}

namespace PowerArhitecture.Authentication
{
	public partial class AuthenticationSettings : Specifications.IAuthenticationSettings
	{
		public AuthenticationSettings()
		{
		}
		public virtual string SystemUserPassword 
		{ 
			get { return AppConfiguration.GetSetting<string>("PowerArhitecture.Authentication.SystemUserPassword:string"); } 
		}
		public virtual string SystemUserName 
		{ 
			get { return AppConfiguration.GetSetting<string>("PowerArhitecture.Authentication.SystemUserName:string"); } 
		}
		public virtual string UserClass 
		{ 
			get { return AppConfiguration.GetSetting<string>("PowerArhitecture.Authentication.UserClass:string"); } 
		}
		public virtual string OrganizationClass 
		{ 
			get { return AppConfiguration.GetSetting<string>("PowerArhitecture.Authentication.OrganizationClass:string"); } 
		}
		public virtual string AdditionalUserIncludes 
		{ 
			get { return AppConfiguration.GetSetting<string>("PowerArhitecture.Authentication.AdditionalUserIncludes:string"); } 
		}
	}

	public class AuthenticationSettingsRegistration : NinjectModule
	{
		public override void Load()
		{
			Bind<Specifications.IAuthenticationSettings>().To<AuthenticationSettings>().InSingletonScope();
		}
	}
}

namespace PowerArhitecture.Authentication.Specifications
{
	public interface IAuthenticationSettings
	{
		string SystemUserPassword { get; }
		string SystemUserName { get; }
		string UserClass { get; }
		string OrganizationClass { get; }
		string AdditionalUserIncludes { get; }
	}
}

