
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments

using System;
using Ninject.Modules;
using PowerArhitecture.Common.Configuration;


namespace PowerArhitecture.DataCaching.Settings
{
	public static class DataCachingSettingKeys
	{
		public const string IsMaster = "PowerArhitecture.DataCaching.IsMaster:bool";
	}
}


namespace PowerArhitecture.DataCaching.Settings
{
}

namespace PowerArhitecture.DataCaching
{
	public partial class DataCachingSettings : Specifications.IDataCachingSettings
	{
		public DataCachingSettings()
		{
		}
		public virtual bool IsMaster 
		{ 
			get { return AppConfiguration.GetSetting<bool>("PowerArhitecture.DataCaching.IsMaster:bool"); } 
		}
	}

	public class DataCachingSettingsRegistration : NinjectModule
	{
		public override void Load()
		{
			Bind<Specifications.IDataCachingSettings>().To<DataCachingSettings>().InSingletonScope();
		}
	}
}

namespace PowerArhitecture.DataCaching.Specifications
{
	public interface IDataCachingSettings
	{
		bool IsMaster { get; }
	}
}

